---
language: python
python: "2.7"

# Use the new container infrastructure.
sudo: false

# Install Python package manager.
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible.
  - pip install ansible

  # Check ansible version.
  - ansible --version

  # Create ansible.cfg with correct roles_path.
  - printf '[defaults]\nroles_path=../' > ansible.cfg

script:
  # Role syntax check.
  - ansible-playbook tests/test.yml -i 'localhost,' --syntax-check
  # Run test playbook.
  - ansible-playbook tests/test.yml -i 'localhost,' --connection=local

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
