---
branches:
  only:
    - 1.x.x
    - /^\d+\.\d+\.\d+$/

jobs:
  fast_finish: true

  include:
    - &Test

      name: Ubuntu 16.04 / Ansible 2.8 / PHP 7.2

      os: linux

      dist: xenial

      cache:
        pip: true

      language: python

      python: 3.6

      env: MOLECULE_PLATFORM=ubuntu:16.04 ANSIBLE_VERSION=2.8 PHP_VERSION=7.2

      before_install:
        - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        - sudo apt-get update
        - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

      install:
        - pip install ansible~=${ANSIBLE_VERSION} ansible-lint docker molecule~=3.0.8

      script:
        - molecule test

    - <<: *Test

      name: Ubuntu 16.04 / Ansible 2.8 / PHP 7.3

      env: MOLECULE_PLATFORM=ubuntu:16.04 ANSIBLE_VERSION=2.9 PHP_VERSION=7.3

    - <<: *Test

      name: Ubuntu 18.04 / Ansible 2.9 / PHP 7.4

      env: MOLECULE_PLATFORM=ubuntu:18.04 ANSIBLE_VERSION=2.9 PHP_VERSION=7.4

    - <<: *Test

      name: Ubuntu 20.04 / Ansible 2.9 / PHP 7.4

      env: MOLECULE_PLATFORM=ubuntu:20.04 ANSIBLE_VERSION=2.10.0a1 PHP_VERSION=7.4

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
