---
# Configure PHP CLI.
- name: Configure PHP CLI, section {{ php_configuration_cli_section }}
  ini_file:
    dest: /etc/php/{{ php_version }}/cli/php.ini
    section: "{{ php_configuration_cli_section }}"
    option: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  with_dict:
    "{{ php_configuration_cli[php_configuration_cli_section] }}"
