---
- name: Get the current PHP version for Apache2
  ansible.builtin.shell: |
    set -o pipefail
    ls /etc/apache2/mods-enabled/ |
    grep -oP 'php(\d\.\d)\.load' |
    grep -oP '\d\.\d'
  args:
    executable: /bin/bash
  register: php_apache2_version
  changed_when: false
  failed_when: php_apache2_version.stderr | length > 0

- name: Disable the current PHP version for Apache2 (if exists)
  ansible.builtin.command: "a2dismod php{{ item }}"
  register: a2dismod_cmd
  loop: "{{ php_apache2_version.stdout_lines }}"
  when:
    item != php_version | string
  changed_when: '"To activate the new configuration" in a2dismod_cmd.stdout'
  failed_when: '"ERROR" in a2dismod_cmd.stderr'
  notify:
    - Restart web server

- name: Enable a new PHP version for Apache2
  ansible.builtin.command: "a2enmod php{{ php_version }}"
  register: a2enmod_cmd
  when:
    php_apache2_version.stdout != php_version | string
  changed_when: '"To activate the new configuration" in a2enmod_cmd.stdout'
  failed_when: '"ERROR" in a2enmod_cmd.stderr'
  notify:
    - Restart web server
