---
# Configure PHP.
- name: Configure PHP, section {{ php_configuration_section }}
  ini_file:
    dest: /etc/php/{{ php_version }}/{{ php_web_server_deamon }}/php.ini
    section: "{{ php_configuration_section }}"
    option: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  with_dict:
    "{{ php_configuration[php_configuration_section] }}"
  notify:
    - Restart web server
