---
# Make sure PHP version is set.
- name: Define PHP version to install
  set_fact:
    php_version: 7.1
  when: php_version == ''

# Make sure web server daemon is set.
- name: Define web server daemon
  set_fact:
    php_web_server_daemon: apache2
  when: php_web_server_daemon == ''

# Ensure base packages are present.
- name: Install base packages
  apt:
    name:
      - software-properties-common
    state: present
    update_cache: true
    cache_valid_time: 86400

# Add the main PPA for PHP. See https://launchpad.net/~ondrej/+archive/ubuntu/php
- name: Add the main PPA for PHP
  apt_repository:
    repo: ppa:ondrej/php
    state: present
    update_cache: true

# Install PHP.
- name: Install PHP
  apt:
    name: php{{ php_version }}
    state: present
    update_cache: true
    cache_valid_time: 86400
  notify:
    - Restart web server

- name: Generate list of PHP extensions names to install
  command: "echo php{{ php_version }}-{{ item }}"
  register: php_extenstions_names
  loop: "{{ php_extensions | flatten(levels=1) }}"
  changed_when: false

# Install PHP extensions.
- name: Install PHP extensions
  apt:
    name: "{{ php_extenstions_names.results | map(attribute='stdout') | list }}"
    state: present
  notify:
    - Restart web server

# Configure PHP.
- include: configure_php.yml
  with_items:
    "{{ php_configuration }}"
  loop_control:
    loop_var: php_configuration_section

# Configure PHP CLI.
- include: configure_php_cli.yml
  with_items:
    "{{ php_cli_configuration }}"
  loop_control:
    loop_var: php_cli_configuration_section

# Configure PHP extensions.
- include: configure_php_extensions.yml
  with_items:
    "{{ php_extensions_configuration }}"
  loop_control:
    loop_var: php_extension_configuration
