---
- hosts: all
  become: true

  pre_tasks:

    - name: Ensure Ansible temp directory exists
      file:
        path: /tmp/ansible
        state: directory
        mode: 0777

    - name: Update apt cache
      apt:
        update_cache: true
        cache_valid_time: 180

  roles:
    - t2l.php

  vars:
    ansible_python_interpreter: /usr/bin/python3
    php_extensions:
      - gd
      - mysql
      - xdebug
      - zip
    php_configuration:
      Date:
        date.timezone: Europe/Kiev
      PHP:
        memory_limit: 256M
    php_cli_configuration:
      Date:
        date.timezone: Europe/Kiev
    php_extensions_configuration:
      xdebug:
        xdebug.mode: debug
        xdebug.discover_client_host: 'true'
