---
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-data:
      extends: default
      rules:
        line-length: disable
platforms:
  - name: draft
    image: "${MOLECULE_PLATFORM}"
    capabilities:
      - SYS_ADMIN
      - NET_ADMIN
    env:
      # The /etc/default/locale file is loaded by PAM; see /etc/pam.d/login
      # for example. However, PAM is not invoked when running a command in a
      # Docker container.
      LANG: en_US.UTF-8
      LC_ALL: en_US.UTF-8
provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /tmp/ansible
    ssh_connection:
      pipelining: true
  inventory:
    group_vars:
      all:
        php_version: ${PHP_VERSION}
  lint:
    name: ansible-lint
